// <auto-generated />
using System;
using DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataContext.Migrations
{
    [DbContext(typeof(AOEStatsDbContext))]
    partial class AOEStatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Domain.Models.UnitStatsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attributes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Civilization")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<double>("FoodCost")
                        .HasColumnType("REAL");

                    b.Property<double>("GoldCost")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StoneCost")
                        .HasColumnType("REAL");

                    b.Property<int>("UnitType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoLink")
                        .HasColumnType("TEXT");

                    b.Property<double>("WoodCost")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("UnitStatsItems");
                });
#pragma warning restore 612, 618
        }
    }
}
